# Generated by Django 4.2.22 on 2026-03-01 15:10

from django.db import migrations, models
import django_dto_field.dto_field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelForTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_json_field", models.JSONField(null=True)),
                ("dict_dto_field", django_dto_field.dto_field.DTOField()),
                ("none_dto_field", django_dto_field.dto_field.DTOField(null=True)),
            ],
        ),
    ]
