# Generated by Django 4.2.22 on 2025-09-17 21:36

from django.db import migrations, models
import django_dict_field.params_field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelForTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_dict_field", django_dict_field.params_field.DictField()),
            ],
        ),
    ]
